#include "ft_strace.h"

void handle_signals(pid_t tracee_pid, int status)
{
	if (WIFEXITED(status))
	{
		siginfo_t siginfo;
		ptrace(PTRACE_GETSIGINFO, tracee_pid, NULL, &siginfo);
		printf("Received signal %d (%s)\n", siginfo.si_signo, strsignal(siginfo.si_signo));
	}

	/* If child has stopped by a signal */
	if (WIFSTOPPED(status))
	{
		int sig = WSTOPSIG(status);
		// Ignore SIGTRAP signals generated by syscall
		if (sig != (SIGTRAP | 0x80))
		{
			siginfo_t siginfo;
			ptrace(PTRACE_GETSIGINFO, tracee_pid, NULL, &siginfo);
			printf("Received signal %d (%s)\n", siginfo.si_signo, strsignal(siginfo.si_signo));
		}
	}
}
