#ifndef SYSCALLENT_H
#define SYSCALLENT_H

typedef enum
{
	ARG_TYPE_INT,
	ARG_TYPE_LONG,
	ARG_TYPE_PTR,
	ARG_TYPE_STR,
	ARG_TYPE_SIZE,
} arg_type;

typedef struct syscall_entry_s
{
	int number;
	const char *name;
	int num_args;
	arg_type arg_types[6];
} syscall_entry_t;

static syscall_entry_t syscall_table[] = {
	{0, "read", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{1, "write", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_SIZE}},
	{2, "open", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{3, "close", 1, {ARG_TYPE_INT}},
	{4, "stat", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{5, "fstat", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{6, "lstat", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{7, "poll", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{8, "lseek", 3, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{9, "mmap", 6, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG}},
	{10, "mprotect", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{11, "munmap", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{12, "brk", 1, {ARG_TYPE_PTR}},
	{13, "rt_sigaction", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{14, "rt_sigprocmask", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{15, "rt_sigreturn", 0, {}},
	{16, "ioctl", 3, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_PTR}},
	{17, "pread64", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_LONG}},
	{18, "pwrite64", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_LONG}},
	{19, "readv", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{20, "writev", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{21, "access", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{22, "pipe", 1, {ARG_TYPE_PTR}},
	{23, "select", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{24, "sched_yield", 0, {}},
	{25, "mremap", 5, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{26, "msync", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{27, "mincore", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{28, "madvise", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{29, "shmget", 3, {ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{30, "shmat", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{31, "shmctl", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{32, "dup", 1, {ARG_TYPE_INT}},
	{33, "dup2", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{34, "pause", 0, {}},
	{35, "nanosleep", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{36, "getitimer", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{37, "alarm", 1, {ARG_TYPE_INT}},
	{38, "setitimer", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{39, "getpid", 0, {}},
	{40, "sendfile", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{41, "socket", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{42, "connect", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{43, "accept", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{44, "sendto", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{45, "recvfrom", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{46, "sendmsg", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{47, "recvmsg", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{48, "shutdown", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{49, "bind", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{50, "listen", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{51, "getsockname", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{52, "getpeername", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{53, "socketpair", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{54, "setsockopt", 5, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{55, "getsockopt", 5, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{56, "clone", 5, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{57, "fork", 0, {}},
	{58, "vfork", 0, {}},
	{59, "execve", 3, {ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{60, "exit", 1, {ARG_TYPE_INT}},
	{61, "wait4", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{62, "kill", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{63, "uname", 1, {ARG_TYPE_PTR}},
	{64, "semget", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{65, "semop", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{66, "semctl", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{67, "shmdt", 1, {ARG_TYPE_PTR}},
	{68, "msgget", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{69, "msgsnd", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{70, "msgrcv", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{71, "msgctl", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{72, "fcntl", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{73, "flock", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{74, "fsync", 1, {ARG_TYPE_INT}},
	{75, "fdatasync", 1, {ARG_TYPE_INT}},
	{76, "truncate", 2, {ARG_TYPE_STR, ARG_TYPE_LONG}},
	{77, "ftruncate", 2, {ARG_TYPE_INT, ARG_TYPE_LONG}},
	{78, "getdents", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{79, "getcwd", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{80, "chdir", 1, {ARG_TYPE_STR}},
	{81, "fchdir", 1, {ARG_TYPE_INT}},
	{82, "rename", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{83, "mkdir", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{84, "rmdir", 1, {ARG_TYPE_STR}},
	{85, "creat", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{86, "link", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{87, "unlink", 1, {ARG_TYPE_STR}},
	{88, "symlink", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{89, "readlink", 3, {ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{90, "chmod", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{91, "fchmod", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{92, "chown", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{93, "fchown", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{94, "lchown", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{95, "umask", 1, {ARG_TYPE_INT}},
	{96, "gettimeofday", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{97, "getrlimit", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{98, "getrusage", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{99, "sysinfo", 1, {ARG_TYPE_PTR}},
	{100, "times", 1, {ARG_TYPE_PTR}},
	{101, "ptrace", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{102, "getuid", 0, {}},
	{103, "syslog", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{104, "getgid", 0, {}},
	{105, "setuid", 1, {ARG_TYPE_INT}},
	{106, "setgid", 1, {ARG_TYPE_INT}},
	{107, "geteuid", 0, {}},
	{108, "getegid", 0, {}},
	{109, "setpgid", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{110, "getppid", 0, {}},
	{111, "getpgrp", 0, {}},
	{112, "setsid", 0, {}},
	{113, "setreuid", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{114, "setregid", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{115, "getgroups", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{116, "setgroups", 2, {ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{117, "setresuid", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{118, "getresuid", 3, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{119, "setresgid", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{120, "getresgid", 3, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{121, "getpgid", 1, {ARG_TYPE_INT}},
	{122, "setfsuid", 1, {ARG_TYPE_INT}},
	{123, "setfsgid", 1, {ARG_TYPE_INT}},
	{124, "getsid", 1, {ARG_TYPE_INT}},
	{125, "capget", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{126, "capset", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{127, "rt_sigpending", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{128, "rt_sigtimedwait", 4, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{129, "rt_sigqueueinfo", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{130, "rt_sigsuspend", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{131, "sigaltstack", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{132, "utime", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{133, "mknod", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{134, "uselib", 1, {ARG_TYPE_STR}},
	{135, "personality", 1, {ARG_TYPE_LONG}},
	{136, "ustat", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{137, "statfs", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{138, "fstatfs", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{139, "sysfs", 3, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_PTR}},
	{140, "getpriority", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{141, "setpriority", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{142, "sched_setparam", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{143, "sched_getparam", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{144, "sched_setscheduler", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{145, "sched_getscheduler", 1, {ARG_TYPE_INT}},
	{146, "sched_get_priority_max", 1, {ARG_TYPE_INT}},
	{147, "sched_get_priority_min", 1, {ARG_TYPE_INT}},
	{148, "sched_rr_get_interval", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{149, "mlock", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{150, "munlock", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{151, "mlockall", 1, {ARG_TYPE_INT}},
	{152, "munlockall", 0, {}},
	{153, "vhangup", 0, {}},
	{154, "modify_ldt", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_LONG}},
	{155, "pivot_root", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{156, "_sysctl", 1, {ARG_TYPE_PTR}},
	{157, "prctl", 5, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG}},
	{158, "arch_prctl", 2, {ARG_TYPE_INT, ARG_TYPE_LONG}},
	{159, "adjtimex", 1, {ARG_TYPE_PTR}},
	{160, "setrlimit", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{161, "chroot", 1, {ARG_TYPE_STR}},
	{162, "sync", 0, {}},
	{163, "acct", 1, {ARG_TYPE_STR}},
	{164, "settimeofday", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{165, "mount", 5, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_LONG, ARG_TYPE_PTR}},
	{166, "umount2", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{167, "swapon", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{168, "swapoff", 1, {ARG_TYPE_STR}},
	{169, "reboot", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{170, "sethostname", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{171, "setdomainname", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{172, "iopl", 1, {ARG_TYPE_INT}},
	{173, "ioperm", 3, {ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{174, "create_module", 2, {ARG_TYPE_STR, ARG_TYPE_SIZE}},
	{175, "init_module", 3, {ARG_TYPE_PTR, ARG_TYPE_LONG, ARG_TYPE_STR}},
	{176, "delete_module", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{177, "get_kernel_syms", 1, {ARG_TYPE_PTR}},
	{178, "query_module", 5, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{179, "quotactl", 4, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR}},
	{180, "nfsservctl", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{181, "getpmsg", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{182, "putpmsg", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{183, "afs_syscall", 0, {}},
	{184, "tuxcall", 0, {}},
	{185, "security", 0, {}},
	{186, "gettid", 0, {}},
	{187, "readahead", 3, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_SIZE}},
	{188, "setxattr", 5, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{189, "lsetxattr", 5, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{190, "fsetxattr", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{191, "getxattr", 4, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{192, "lgetxattr", 4, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{193, "fgetxattr", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{194, "listxattr", 3, {ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{195, "llistxattr", 3, {ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{196, "flistxattr", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{197, "removexattr", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{198, "lremovexattr", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{199, "fremovexattr", 2, {ARG_TYPE_INT, ARG_TYPE_STR}},
	{200, "tkill", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{201, "time", 1, {ARG_TYPE_PTR}},
	{202, "futex", 6, {ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{203, "sched_setaffinity", 3, {ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{204, "sched_getaffinity", 3, {ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{205, "set_thread_area", 1, {ARG_TYPE_PTR}},
	{206, "io_setup", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{207, "io_destroy", 1, {ARG_TYPE_LONG}},
	{208, "io_getevents", 5, {ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{209, "io_submit", 3, {ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_PTR}},
	{210, "io_cancel", 3, {ARG_TYPE_LONG, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{211, "get_thread_area", 1, {ARG_TYPE_PTR}},
	{212, "lookup_dcookie", 3, {ARG_TYPE_LONG, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{213, "epoll_create", 1, {ARG_TYPE_INT}},
	{214, "epoll_ctl_old", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{215, "epoll_wait_old", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{216, "remap_file_pages", 5, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{217, "getdents64", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{218, "set_tid_address", 1, {ARG_TYPE_PTR}},
	{219, "restart_syscall", 0, {}},
	{220, "semtimedop", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{221, "fadvise64", 4, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{222, "timer_create", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{223, "timer_settime", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{224, "timer_gettime", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{225, "timer_getoverrun", 1, {ARG_TYPE_INT}},
	{226, "timer_delete", 1, {ARG_TYPE_INT}},
	{227, "clock_settime", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{228, "clock_gettime", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{229, "clock_getres", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{230, "clock_nanosleep", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{231, "exit_group", 1, {ARG_TYPE_INT}},
	{232, "epoll_wait", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{233, "epoll_ctl", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{234, "tgkill", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{235, "utimes", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{236, "vserver", 0, {}},
	{237, "mbind", 6, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{238, "set_mempolicy", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{239, "get_mempolicy", 5, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{240, "mq_open", 4, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{241, "mq_unlink", 1, {ARG_TYPE_STR}},
	{242, "mq_timedsend", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{243, "mq_timedreceive", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{244, "mq_notify", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{245, "mq_getsetattr", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{246, "kexec_load", 4, {ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_PTR, ARG_TYPE_LONG}},
	{247, "waitid", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{248, "add_key", 5, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{249, "request_key", 4, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_INT}},
	{250, "keyctl", 5, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG}},
	{251, "ioprio_set", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{252, "ioprio_get", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{253, "inotify_init", 0, {}},
	{254, "inotify_add_watch", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{255, "inotify_rm_watch", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{256, "migrate_pages", 4, {ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{257, "openat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{258, "mkdirat", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{259, "mknodat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{260, "fchownat", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{261, "futimesat", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR}},
	{262, "newfstatat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{263, "unlinkat", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{264, "renameat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_STR}},
	{265, "linkat", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{266, "symlinkat", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_STR}},
	{267, "readlinkat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{268, "fchmodat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{269, "faccessat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{270, "pselect6", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{271, "ppoll", 5, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{272, "unshare", 1, {ARG_TYPE_INT}},
	{273, "set_robust_list", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{274, "get_robust_list", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{275, "splice", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{276, "tee", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{277, "sync_file_range", 4, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{278, "vmsplice", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{279, "move_pages", 6, {ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{280, "utimensat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{281, "epoll_pwait", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{282, "signalfd", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{283, "timerfd_create", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{284, "eventfd", 1, {ARG_TYPE_INT}},
	{285, "fallocate", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_LONG}},
	{286, "timerfd_settime", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{287, "timerfd_gettime", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{288, "accept4", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{289, "signalfd4", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{290, "eventfd2", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{291, "epoll_create1", 1, {ARG_TYPE_INT}},
	{292, "dup3", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{293, "pipe2", 2, {ARG_TYPE_PTR, ARG_TYPE_INT}},
	{294, "inotify_init1", 1, {ARG_TYPE_INT}},
	{295, "preadv", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_LONG}},
	{296, "pwritev", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_LONG}},
	{297, "rt_tgsigqueueinfo", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{298, "perf_event_open", 5, {ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG}},
	{299, "recvmmsg", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{300, "fanotify_init", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{301, "fanotify_mark", 5, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_INT, ARG_TYPE_STR}},
	{302, "prlimit64", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{303, "name_to_handle_at", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{304, "open_by_handle_at", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{305, "clock_adjtime", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{306, "syncfs", 1, {ARG_TYPE_INT}},
	{307, "sendmmsg", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{308, "setns", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{309, "getcpu", 3, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{310, "process_vm_readv", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_LONG}},
	{311, "process_vm_writev", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_LONG}},
	{312, "kcmp", 5, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_LONG}},
	{313, "finit_module", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{314, "sched_setattr", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{315, "sched_getattr", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{316, "renameat2", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{317, "seccomp", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{318, "getrandom", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{319, "memfd_create", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{320, "kexec_file_load", 5, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_STR, ARG_TYPE_LONG}},
	{321, "bpf", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{322, "execveat", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{323, "userfaultfd", 1, {ARG_TYPE_INT}},
	{324, "membarrier", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{325, "mlock2", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{326, "copy_file_range", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{327, "preadv2", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{328, "pwritev2", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{329, "pkey_mprotect", 4, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_INT}},
	{330, "pkey_alloc", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{331, "pkey_free", 1, {ARG_TYPE_INT}},
	{332, "statx", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{333, "io_pgetevents", 5, {ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{334, "rseq", 4, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_INT}},
	{335, "uretprobe", 0, {}}};

#endif // SYSCALLENT_H
