#ifndef SYSCALLENT_X32_H
#define SYSCALLENT_X32_H

#include "ft_strace.h"

/*
 * https://github.com/torvalds/linux/blob/master/arch/x86/entry/syscalls/syscall_32.tbl
 *
 * This table defines system call entries for 32-bit binaries.
 * Each entry contains:
 *   - The syscall number
 *   - The syscall name (as found in Linux source or man pages)
 *   - The number of arguments
 *   - The types of those arguments (e.g., integer, pointer, size, etc.)
 *
 * The table includes a comprehensive list of x86 32-bit system calls.
 * For brevity, only a portion of these entries is shown here.
 */

static t_syscall_entry syscall_table_x32[] = {
	{0, "restart_syscall", 0, {}},
	{1, "exit", 1, {ARG_TYPE_INT}},
	{2, "fork", 0, {}},
	{3, "read", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{4, "write", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_SIZE}},
	{5, "open", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{6, "close", 1, {ARG_TYPE_INT}},
	{7, "waitpid", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{8, "creat", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{9, "link", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{10, "unlink", 1, {ARG_TYPE_STR}},
	{11, "execve", 3, {ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{12, "chdir", 1, {ARG_TYPE_STR}},
	{13, "time", 1, {ARG_TYPE_PTR}},
	{14, "mknod", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{15, "chmod", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{16, "lchown", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{17, "break", 0, {}},
	{18, "oldstat", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{19, "lseek", 3, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{20, "getpid", 0, {}},
	{21, "mount", 4, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_LONG}},
	{22, "umount", 1, {ARG_TYPE_STR}},
	{23, "setuid", 1, {ARG_TYPE_INT}},
	{24, "getuid", 0, {}},
	{25, "stime", 1, {ARG_TYPE_PTR}},
	{26, "ptrace", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{27, "alarm", 1, {ARG_TYPE_INT}},
	{28, "oldfstat", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{29, "pause", 0, {}},
	{30, "utime", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{31, "stty", 0, {}},
	{32, "gtty", 0, {}},
	{33, "access", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{34, "nice", 1, {ARG_TYPE_INT}},
	{35, "ftime", 1, {ARG_TYPE_PTR}},
	{36, "sync", 0, {}},
	{37, "kill", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{38, "rename", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{39, "mkdir", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{40, "rmdir", 1, {ARG_TYPE_STR}},
	{41, "dup", 1, {ARG_TYPE_INT}},
	{42, "pipe", 1, {ARG_TYPE_PTR}},
	{43, "times", 1, {ARG_TYPE_PTR}},
	{44, "prof", 0, {}},
	{45, "brk", 1, {ARG_TYPE_PTR}},
	{46, "setgid", 1, {ARG_TYPE_INT}},
	{47, "getgid", 0, {}},
	{48, "signal", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{49, "geteuid", 0, {}},
	{50, "getegid", 0, {}},
	{51, "acct", 1, {ARG_TYPE_STR}},
	{52, "umount2", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{53, "lock", 0, {}},
	{54, "ioctl", 3, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_PTR}},
	{55, "fcntl", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{56, "mpx", 0, {}},
	{57, "setpgid", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{58, "ulimit", 2, {ARG_TYPE_INT, ARG_TYPE_LONG}},
	{59, "oldolduname", 1, {ARG_TYPE_PTR}},
	{60, "umask", 1, {ARG_TYPE_INT}},
	{61, "chroot", 1, {ARG_TYPE_STR}},
	{62, "ustat", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{63, "dup2", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{64, "getppid", 0, {}},
	{65, "getpgrp", 0, {}},
	{66, "setsid", 0, {}},
	{67, "sigaction", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{68, "sgetmask", 0, {}},
	{69, "ssetmask", 1, {ARG_TYPE_LONG}},
	{70, "setreuid", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{71, "setregid", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{72, "sigsuspend", 1, {ARG_TYPE_PTR}},
	{73, "sigpending", 1, {ARG_TYPE_PTR}},
	{74, "sethostname", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{75, "setrlimit", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{76, "getrlimit", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{77, "getrusage", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{78, "gettimeofday", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{79, "settimeofday", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{80, "getgroups", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{81, "setgroups", 2, {ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{82, "select", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{83, "symlink", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{84, "oldlstat", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{85, "readlink", 3, {ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{86, "uselib", 1, {ARG_TYPE_STR}},
	{87, "swapon", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{88, "reboot", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{89, "readdir", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{90, "mmap", 6, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG}},
	{91, "munmap", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{92, "truncate", 2, {ARG_TYPE_STR, ARG_TYPE_LONG}},
	{93, "ftruncate", 2, {ARG_TYPE_INT, ARG_TYPE_LONG}},
	{94, "fchmod", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{95, "fchown", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{96, "getpriority", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{97, "setpriority", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{98, "profil", 4, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{99, "statfs", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{100, "fstatfs", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{101, "ioperm", 3, {ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{102, "socketcall", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{103, "syslog", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{104, "setitimer", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{105, "getitimer", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{106, "stat", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{107, "lstat", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{108, "fstat", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{109, "olduname", 1, {ARG_TYPE_PTR}},
	{110, "iopl", 1, {ARG_TYPE_INT}},
	{111, "vhangup", 0, {}},
	{112, "idle", 0, {}},
	{113, "vm86old", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{114, "wait4", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{115, "swapoff", 1, {ARG_TYPE_STR}},
	{116, "sysinfo", 1, {ARG_TYPE_PTR}},
	{117, "ipc", 6, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{118, "fsync", 1, {ARG_TYPE_INT}},
	{119, "sigreturn", 0, {}},
	{120, "clone", 5, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{121, "setdomainname", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{122, "uname", 1, {ARG_TYPE_PTR}},
	{123, "modify_ldt", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_LONG}},
	{124, "adjtimex", 1, {ARG_TYPE_PTR}},
	{125, "mprotect", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{126, "sigprocmask", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{127, "create_module", 2, {ARG_TYPE_STR, ARG_TYPE_SIZE}},
	{128, "init_module", 3, {ARG_TYPE_PTR, ARG_TYPE_LONG, ARG_TYPE_STR}},
	{129, "delete_module", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{130, "get_kernel_syms", 1, {ARG_TYPE_PTR}},
	{131, "quotactl", 4, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR}},
	{132, "getpgid", 1, {ARG_TYPE_INT}},
	{133, "fchdir", 1, {ARG_TYPE_INT}},
	{134, "bdflush", 2, {ARG_TYPE_INT, ARG_TYPE_LONG}},
	{135, "sysfs", 3, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_PTR}},
	{136, "personality", 1, {ARG_TYPE_LONG}},
	{137, "afs_syscall", 0, {}},
	{138, "setfsuid", 1, {ARG_TYPE_INT}},
	{139, "setfsgid", 1, {ARG_TYPE_INT}},
	{140, "_llseek", 5, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{141, "getdents", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{142, "_newselect", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{143, "flock", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{144, "msync", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{145, "readv", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{146, "writev", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{147, "getsid", 1, {ARG_TYPE_INT}},
	{148, "fdatasync", 1, {ARG_TYPE_INT}},
	{149, "_sysctl", 1, {ARG_TYPE_PTR}},
	{150, "mlock", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{151, "munlock", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{152, "mlockall", 1, {ARG_TYPE_INT}},
	{153, "munlockall", 0, {}},
	{154, "sched_setparam", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{155, "sched_getparam", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{156, "sched_setscheduler", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{157, "sched_getscheduler", 1, {ARG_TYPE_INT}},
	{158, "sched_yield", 0, {}},
	{159, "sched_get_priority_max", 1, {ARG_TYPE_INT}},
	{160, "sched_get_priority_min", 1, {ARG_TYPE_INT}},
	{161, "sched_rr_get_interval", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{162, "nanosleep", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{163, "mremap", 5, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{164, "setresuid", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{165, "getresuid", 3, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{166, "vm86", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{167, "query_module", 4, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{168, "poll", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{169, "nfsservctl", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{170, "setresgid", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{171, "getresgid", 3, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{172, "prctl", 5, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG}},
	{173, "rt_sigreturn", 0, {}},
	{174, "rt_sigaction", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{175, "rt_sigprocmask", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{176, "rt_sigpending", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{177, "rt_sigtimedwait", 4, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{178, "rt_sigqueueinfo", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{179, "rt_sigsuspend", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{180, "pread64", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_LONG}},
	{181, "pwrite64", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_LONG}},
	{182, "chown", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{183, "getcwd", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{184, "capget", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{185, "capset", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{186, "sigaltstack", 2, {ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{187, "sendfile", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{188, "getpmsg", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{189, "putpmsg", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{190, "vfork", 0, {}},
	{191, "ugetrlimit", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{192, "mmap2", 6, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG}},
	{193, "truncate64", 2, {ARG_TYPE_STR, ARG_TYPE_LONG}},
	{194, "ftruncate64", 2, {ARG_TYPE_INT, ARG_TYPE_LONG}},
	{195, "stat64", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{196, "lstat64", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{197, "fstat64", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{198, "lchown32", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{199, "getuid32", 0, {}},
	{200, "getgid32", 0, {}},
	{201, "geteuid32", 0, {}},
	{202, "getegid32", 0, {}},
	{203, "setreuid32", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{204, "setregid32", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{205, "getgroups32", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{206, "setgroups32", 2, {ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{207, "fchown32", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{208, "setresuid32", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{209, "getresuid32", 3, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{210, "setresgid32", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{211, "getresgid32", 3, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{212, "chown32", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{213, "setuid32", 1, {ARG_TYPE_INT}},
	{214, "setgid32", 1, {ARG_TYPE_INT}},
	{215, "setfsuid32", 1, {ARG_TYPE_INT}},
	{216, "setfsgid32", 1, {ARG_TYPE_INT}},
	{217, "pivot_root", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{218, "mincore", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{219, "madvise", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{220, "getdents64", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{221, "fcntl64", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{224, "gettid", 0, {}},
	{225, "readahead", 3, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_SIZE}},
	{226, "setxattr", 5, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{227, "lsetxattr", 5, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{228, "fsetxattr", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{229, "getxattr", 4, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{230, "lgetxattr", 4, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{231, "fgetxattr", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{232, "listxattr", 3, {ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{233, "llistxattr", 3, {ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{234, "flistxattr", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{235, "removexattr", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{236, "lremovexattr", 2, {ARG_TYPE_STR, ARG_TYPE_STR}},
	{237, "fremovexattr", 2, {ARG_TYPE_INT, ARG_TYPE_STR}},
	{238, "tkill", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{239, "sendfile64", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{240, "futex", 6, {ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{241, "sched_setaffinity", 3, {ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{242, "sched_getaffinity", 3, {ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{243, "set_thread_area", 1, {ARG_TYPE_PTR}},
	{244, "get_thread_area", 1, {ARG_TYPE_PTR}},
	{245, "io_setup", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{246, "io_destroy", 1, {ARG_TYPE_LONG}},
	{247, "io_getevents", 5, {ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{248, "io_submit", 3, {ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_PTR}},
	{249, "io_cancel", 3, {ARG_TYPE_LONG, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{250, "fadvise64", 4, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{252, "exit_group", 1, {ARG_TYPE_INT}},
	{254, "epoll_create", 1, {ARG_TYPE_INT}},
	{255, "epoll_ctl", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{256, "epoll_wait", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{257, "remap_file_pages", 5, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{258, "set_tid_address", 1, {ARG_TYPE_PTR}},
	{259, "timer_create", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{260, "timer_settime", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{261, "timer_gettime", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{262, "timer_getoverrun", 1, {ARG_TYPE_INT}},
	{263, "timer_delete", 1, {ARG_TYPE_INT}},
	{264, "clock_settime", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{265, "clock_gettime", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{266, "clock_getres", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{267, "clock_nanosleep", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{268, "statfs64", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{269, "fstatfs64", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{270, "tgkill", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{271, "utimes", 2, {ARG_TYPE_STR, ARG_TYPE_PTR}},
	{272, "fadvise64_64", 4, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{273, "vserver", 0, {}},
	{274, "mbind", 6, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{275, "get_mempolicy", 5, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{276, "set_mempolicy", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{277, "mq_open", 4, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{278, "mq_unlink", 1, {ARG_TYPE_STR}},
	{279, "mq_timedsend", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{280, "mq_timedreceive", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{281, "mq_notify", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{282, "mq_getsetattr", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{283, "kexec_load", 4, {ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_PTR, ARG_TYPE_LONG}},
	{284, "waitid", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{285, "setaltroot", 0, {}},
	{286, "add_key", 5, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{287, "request_key", 4, {ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_INT}},
	{288, "keyctl", 5, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG}},
	{289, "ioprio_set", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{290, "ioprio_get", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{291, "inotify_init", 0, {}},
	{292, "inotify_add_watch", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{293, "inotify_rm_watch", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{294, "migrate_pages", 4, {ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{295, "openat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{296, "mkdirat", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{297, "mknodat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{298, "fchownat", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{299, "futimesat", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR}},
	{300, "fstatat64", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{301, "unlinkat", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{302, "renameat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_STR}},
	{303, "linkat", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{304, "symlinkat", 3, {ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_STR}},
	{305, "readlinkat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{306, "fchmodat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{307, "faccessat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{308, "pselect6", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{309, "ppoll", 5, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{310, "unshare", 1, {ARG_TYPE_INT}},
	{311, "set_robust_list", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{312, "get_robust_list", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{313, "splice", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{314, "sync_file_range", 4, {ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{315, "tee", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{316, "vmsplice", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{317, "move_pages", 6, {ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{318, "getcpu", 3, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{319, "epoll_pwait", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{320, "utimensat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{321, "signalfd", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{322, "timerfd_create", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{323, "eventfd", 1, {ARG_TYPE_INT}},
	{324, "fallocate", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_LONG}},
	{325, "timerfd_settime", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{326, "timerfd_gettime", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{327, "signalfd4", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{328, "eventfd2", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{329, "epoll_create1", 1, {ARG_TYPE_INT}},
	{330, "dup3", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{331, "pipe2", 2, {ARG_TYPE_PTR, ARG_TYPE_INT}},
	{332, "inotify_init1", 1, {ARG_TYPE_INT}},
	{333, "preadv", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_LONG}},
	{334, "pwritev", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_LONG}},
	{335, "rt_tgsigqueueinfo", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{336, "perf_event_open", 5, {ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG}},
	{337, "recvmmsg", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{338, "fanotify_init", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{339, "fanotify_mark", 5, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_INT, ARG_TYPE_STR}},
	{340, "prlimit64", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{341, "name_to_handle_at", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{342, "open_by_handle_at", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{343, "clock_adjtime", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{344, "syncfs", 1, {ARG_TYPE_INT}},
	{345, "sendmmsg", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{346, "setns", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{347, "process_vm_readv", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_LONG}},
	{348, "process_vm_writev", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_LONG}},
	{349, "kcmp", 5, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_LONG}},
	{350, "finit_module", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{351, "sched_setattr", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{352, "sched_getattr", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{353, "renameat2", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{354, "seccomp", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{355, "getrandom", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{356, "memfd_create", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{357, "bpf", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{358, "execveat", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{359, "socket", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{360, "socketpair", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{361, "bind", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{362, "connect", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{363, "listen", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{364, "accept4", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{365, "getsockopt", 5, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{366, "setsockopt", 5, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{367, "getsockname", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{368, "getpeername", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{369, "sendto", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{370, "sendmsg", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{371, "recvfrom", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{372, "recvmsg", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{373, "shutdown", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{374, "userfaultfd", 1, {ARG_TYPE_INT}},
	{375, "membarrier", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{376, "mlock2", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{377, "copy_file_range", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{378, "preadv2", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{379, "pwritev2", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{380, "pkey_mprotect", 4, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_INT}},
	{381, "pkey_alloc", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{382, "pkey_free", 1, {ARG_TYPE_INT}},
	{383, "statx", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{384, "arch_prctl", 2, {ARG_TYPE_INT, ARG_TYPE_LONG}},
	{385, "io_pgetevents", 5, {ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{386, "rseq", 4, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_INT}},
	{393, "semget", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{394, "semctl", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{395, "shmget", 3, {ARG_TYPE_INT, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{396, "shmctl", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{397, "shmat", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{398, "shmdt", 1, {ARG_TYPE_PTR}},
	{399, "msgget", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{400, "msgsnd", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{401, "msgrcv", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_LONG, ARG_TYPE_INT}},
	{402, "msgctl", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{403, "clock_gettime64", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{404, "clock_settime64", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{405, "clock_adjtime64", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{406, "clock_getres_time64", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{407, "clock_nanosleep_time64", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{408, "timer_gettime64", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{409, "timer_settime64", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{410, "timerfd_gettime64", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{411, "timerfd_settime64", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{412, "utimensat_time64", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{413, "pselect6_time64", 6, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{414, "ppoll_time64", 5, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{416, "io_pgetevents_time64", 5, {ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_LONG, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{417, "recvmmsg_time64", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{418, "mq_timedsend_time64", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{419, "mq_timedreceive_time64", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{420, "semtimedop_time64", 4, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR}},
	{421, "rt_sigtimedwait_time64", 4, {ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{422, "futex_time64", 6, {ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{423, "sched_rr_get_interval_time64", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{424, "pidfd_send_signal", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{425, "io_uring_setup", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{426, "io_uring_enter", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{427, "io_uring_register", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{428, "open_tree", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{429, "move_mount", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{430, "fsopen", 2, {ARG_TYPE_STR, ARG_TYPE_INT}},
	{431, "fsconfig", 5, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{432, "fsmount", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{433, "fspick", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT}},
	{434, "pidfd_open", 2, {ARG_TYPE_INT, ARG_TYPE_INT}},
	{435, "clone3", 2, {ARG_TYPE_PTR, ARG_TYPE_SIZE}},
	{436, "close_range", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{437, "openat2", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{438, "pidfd_getfd", 3, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{439, "faccessat2", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{440, "process_madvise", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_INT}},
	{441, "epoll_pwait2", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{442, "mount_setattr", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{443, "quotactl_fd", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR}},
	{444, "landlock_create_ruleset", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{445, "landlock_add_rule", 4, {ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{446, "landlock_restrict_self", 2, {ARG_TYPE_INT, ARG_TYPE_PTR}},
	{447, "memfd_secret", 1, {ARG_TYPE_INT}},
	{448, "process_mrelease", 1, {ARG_TYPE_INT}},
	{449, "futex_waitv", 3, {ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{450, "set_mempolicy_home_node", 5, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{451, "cachestat", 5, {ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{452, "fchmodat2", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{453, "map_shadow_stack", 3, {ARG_TYPE_PTR, ARG_TYPE_SIZE, ARG_TYPE_INT}},
	{454, "futex_wake", 3, {ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT}},
	{455, "futex_wait", 3, {ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{456, "futex_requeue", 5, {ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{457, "statmount", 3, {ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{458, "listmount", 3, {ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{459, "lsm_get_self_attr", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_PTR}},
	{460, "lsm_set_self_attr", 3, {ARG_TYPE_INT, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{461, "lsm_list_modules", 3, {ARG_TYPE_PTR, ARG_TYPE_INT, ARG_TYPE_PTR}},
	{462, "mseal", 1, {ARG_TYPE_INT}},
	{463, "setxattrat", 5, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR, ARG_TYPE_INT}},
	{464, "getxattrat", 4, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_STR, ARG_TYPE_PTR}},
	{465, "listxattrat", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_PTR}},
	{466, "removexattrat", 3, {ARG_TYPE_INT, ARG_TYPE_STR, ARG_TYPE_STR}},
};

#endif // SYSCALLENT_X32_H
